name: Unexpected Outbound Calls
on:
  workflow_dispatch:
jobs:
  unexpected-outbound-calls:
    name: UnexpectedOutboundCalls
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - run: "curl https://google.com -L  || true"
      - run: "curl google.com:80  --connect-timeout 5  || true"
      - run: "curl stepsecurity.io:80  --connect-timeout 5  || true"
      - run: "curl stepsecurity.io:443  --connect-timeout 5 || true"
      - run: "dig google.com"
      - run: "curl https://13.107.21.200 -insecure --connect-timeout 5 || true"
      - run: "curl https://twitter.com -insecure --connect-timeout 5 || true"
      - run: "curl http://www.twitter.com -insecure --connect-timeout 5 || true"
      - run: "curl microsoft.com:443  --connect-timeout 5 || true"
      - run: "curl amazon.com:443  --connect-timeout 5 || true"
      - run: "curl www.amazon.com:443  --connect-timeout 5 || true"
